// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnWUJJ16o-F9CATd6_yNtz34lZ0NybZ00',
    appId: '1:384137530785:web:5478546c653840ac2d4fe0',
    messagingSenderId: '384137530785',
    projectId: 'aniclock',
    authDomain: 'aniclock.firebaseapp.com',
    storageBucket: 'aniclock.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwlMKv6DtwnAwFYgtF1k3TqpXdlP8vk7g',
    appId: '1:384137530785:android:30014597247c95472d4fe0',
    messagingSenderId: '384137530785',
    projectId: 'aniclock',
    storageBucket: 'aniclock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD22jlWbxpwpAtrzlvlAxUXRvYHWE3ToEo',
    appId: '1:384137530785:ios:7ed6498bb148db882d4fe0',
    messagingSenderId: '384137530785',
    projectId: 'aniclock',
    storageBucket: 'aniclock.appspot.com',
    iosClientId: '384137530785-ua12gsdsh965j4ahqdkni091t0ptpggv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProjectName',
  );
}
